settings:
  APP_DISPLAY_NAME: Arcana
  PRODUCTION_APP_NAME: Arcana
  APP_GROUP_IDENTIFIER: group.io.arcana
  BASE_BUNDLE_IDENTIFIER: io.arcana.arcana
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT

  # Classic Element migration intentionally omitted.
  ARCANA_ACCOUNT_PROVIDER: arcana.celesteai.ru
  ARCANA_INVITE_WEB_HOST: arcana.celesteai.ru
  ARCANA_INVITE_DEEP_LINK_URL: "arcana://invite"
